site_name: Tarea 4 ODES
nav:
  - Home: index.md
  - Reference: reference.md
  - About: about.md
theme:
  name: material
  

plugins:
  - search
  - mkdocstrings
  
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
